Repository bachlab/PsPM, pull requests merged in 2019-11, with the labels that each got.

#63 Make sure there is a + marker in sess begin markers in import_viewpoint
  src/Import/viewpoint/import_viewpoint.m
Labels: bug, fixed

#64 Remove all NaN signal test from pspm_glm tests
  test/pspm_glm_test.m
Labels: change request

#65 Extend get_events bugfix according to the previously implemented tests
  src/pspm_get_events.m
  test/pspm_get_events_test.m
Labels: bug, change request

#69 Add badges with various info about repository
  README.md
Labels: improvement

#70 Changed the url in pspm_version.m
  src/pspm_version.m
Labels: change request

#72 Build status badge
  README.md
Labels: improvement

#73 Fix/issue67 : New procedure for catching markers in an Eyelink file
  src/Import/eyelink/import_eyelink.m
  src/pspm_get_events.m
  src/pspm_get_eyelink.m
Labels: bug

#74 Added a warning for markers with same timestamps
  src/Import/eyelink/import_eyelink.m
Labels: change request
