Repository bachlab/PsPM, pull requests merged in 2019-10, with the labels that each got.

#28 Return exit code from pspm_test for jenkins
  test/format_test_results.m
  test/pspm_get_ecg_test.m
  test/pspm_test.m
Labels: in progress, new feature

#33 Disable data filtering in pspm_display and pspm_ecg_editor
  src/pspm_display.m
  src/pspm_ecg_editor.m
Labels: change request, fixed

#36 Issue34 bug prep data
  doc/PsPM_Developers_Guide.lyx
  src/pspm_prepdata.m
  test/pspm_prepdata_test.m
Labels: bug, in progress

#42 Issue #39 pspm_version.m solution for the bug
  src/pspm_version.m
Labels: bug, fixed

#38 Add jekyll and lyx ignore rules to gitignore
  .gitignore
Labels: change request

#44 Fix #43
  doc/PsPM_Manual.lyx
  src/pspm_cfg/pspm_cfg_dcm.m
  src/pspm_dcm.m
Labels: change request

#46 TODO add checkpoints to pspm_transfer_function.m
  src/pspm_transfer_function.m
Labels: TODO

#49 Issue48 hb2hp bug
  src/pspm_hb2hp.m
Labels: bug, fixed

#47 Fixes issue #45: changes in import_viewpoint function
  src/Import/viewpoint/import_viewpoint.m
  src/pspm_get_viewpoint.m
Labels: bug

#52 Bugfix/51
  src/pspm_get_viewpoint.m
Labels: bug, fixed

#55 TODO: test for pspm_hb2hp.m
  src/pspm_hb2hp.m
  test/pspm_hb2hp_test.m
Labels: TODO

#54 Check if a marker only contains one of +,= for splitting
  src/Import/viewpoint/import_viewpoint.m
Labels: bug, fixed

#41 Issue #15: pspm_get_events.m bug with 1st row markers
  src/pspm_get_events.m
Labels: TODO, bug

#59 TODO: test for pspm_butter.m
  src/pspm_butter.m
  test/pspm_butter_test.m
Labels: TODO

#57 Created a warning
  src/pspm_filtfilt.m
Labels: TODO, bug

#58 TODO: test for pspm_filtfilt.m
  src/pspm_filtfilt.m
  test/pspm_filtfilt_test.m
Labels: TODO
