Repository bachlab/PsPM, pull requests merged in 2020-06, with the labels that each got.

#122 Feat/missing epochs file out
  src/pspm_cfg/pspm_cfg_artefact_rm.m
  src/pspm_cfg/pspm_cfg_run_artefact_rm.m
  src/pspm_data_editor.fig
  src/pspm_data_editor.m
  src/pspm_pp.m
  src/pspm_simple_qa.m
  test/pspm_pp_test.m
Labels: waiting for approval

#111 Remove startsWith and endsWith from all functions
  src/Import/eyelink/import_eyelink.m
  src/Import/smi/read_smi_events.m
  src/Import/viewpoint/import_viewpoint.m
  src/backroom/blink_saccade_filtering.m
  src/backroom/set_blinks_saccades_to_nan.m
  src/pspm_blink_saccade_filt.m
  src/pspm_get_viewpoint.m
  src/pspm_load_data.m
  src/pspm_pupil_correct_eyelink.m
  src/pspm_pupil_pp.m
  test/import_eyelink_test.m
  test/import_viewpoint_test.m
  test/set_blinks_saccades_to_nan_test.m
Labels: change request

#116 Add condition to allow plotting any type of marker channel
  src/pspm_display.m
Labels: bug, fixed
