Repository bachlab/PsPM, pull requests merged in 2020-08, with the labels that each got.

#143 pspm_display crashes when loading data
  src/pspm_display.m
Labels: bug, fixed

#132 feat(scanpath-glm): add SPS to first level glm drop down
  doc/PsPM.bib
  doc/PsPM_Developers_Guide.lyx
  doc/PsPM_Manual.lyx
  src/pspm.fig
  src/pspm.m
  src/pspm_bf_spsrf_box.m
  src/pspm_bf_spsrf_gamma.m
  src/pspm_cfg/pspm_cfg_data_preprocessing.m
  src/pspm_cfg/pspm_cfg_gaze_convert.m
  src/pspm_cfg/pspm_cfg_glm_hp_fc.m
  src/pspm_cfg/pspm_cfg_glm_sps.m
  src/pspm_cfg/pspm_cfg_pupil_size_convert.m
  src/pspm_cfg/pspm_cfg_run_gaze_convert.m
  src/pspm_cfg/pspm_cfg_run_pupil_size_convert.m
  src/pspm_compute_visual_angle.m
  src/pspm_compute_visual_angle_core.m
  src/pspm_convert_gaze_distance.m
  src/pspm_convert_pixel2unit.m
  src/pspm_convert_visangle2sps.m
  src/pspm_convert_visangle2sps_core.m
  src/pspm_get_sps.m
  src/pspm_get_sps_l.m
  src/pspm_get_sps_r.m
  src/pspm_glm.m
  src/pspm_init.m
  src/pspm_write_channel.m
  test/pspm_convert_gaze_distance_test.m
  test/pspm_get_sps_test.m
  test/pspm_test.m
  test/pspm_testdata_gen.m
  test/pspm_write_channel_test.m
Labels: improvement

#149 Add flank option in the GUI import module
  src/pspm_cfg/pspm_cfg_import.m
  src/pspm_cfg/pspm_cfg_run_import.m
  src/pspm_get_events.m
  src/pspm_get_eyelink.m
  src/pspm_get_smi.m
  src/pspm_get_viewpoint.m
Labels: improvement, new feature
