Repository bachlab/PsPM, pull requests merged in 2020-02, with the labels that each got.

#89 Use bf_lcrf_gm and bf_ldrf_gm offset to shift the function
  src/pspm_bf_lcrf_gm.m
  src/pspm_bf_ldrf_gm.m
Labels: fixed

#87 Feature82/pspm display
  src/pspm_display.m
Labels: improvement

#94 Change GLM and DCM tutorial data links
  doc/PsPM_Manual.lyx
Labels: documentation

#83 Improvement for pspm_extract_segments
  src/pspm_extract_segments.m
  test/pspm_extract_segments_test.m
Labels: improvement

#92 Feature78/sps spl
  src/pspm_compute_visual_angle.m
  src/pspm_convert_pixel2unit.m
  src/pspm_convert_visangle2sps.m
Labels: fixed, new feature

#91 Feature50/pupil model v2
  src/pspm_init.m
  src/pspm_load1.m
  src/pspm_pfm.m
  test/pspm_load1_test.m
Labels: help wanted, new feature
