Repository bachlab/PsPM, pull requests merged in 2020-09, with the labels that each got.

#156 Feat/dsv 110
  src/pspm_cfg/pspm_cfg_import.m
  src/pspm_cfg/pspm_cfg_run_import.m
  src/pspm_get_csv.m
  src/pspm_get_txt.m
  test/pspm_get_txt_test.m
Labels: improvement

#153 Bugfix/triming indices
  .gitignore
  doc/PsPM_Manual.lyx
  doc/release_notes.tex
  src/pspm_trim.m
  test/pspm_trim_test.m
Labels: bug

#146 feat(filter-epochs): include slope threshold and use array ops instea…
  doc/PsPM_Manual.lyx
  src/pspm_cfg/pspm_cfg_artefact_rm.m
  src/pspm_cfg/pspm_cfg_run_artefact_rm.m
  src/pspm_pp.m
  src/pspm_simple_qa.m
  test/pspm_pp_test.m
Labels: in progress
