Repository bachlab/PsPM, pull requests merged in 2021-07, with the labels that each got.

#271 Add a new feature in return values of pspm_load_data (channel index)
  src/pspm_load_data.m
Labels: Improvement, Waiting for Approval

#274 Fix-272
  src/pspm_split_sessions.m
Labels: Waiting for Approval

#270 Fix issue 269 -- split sessions
  doc/PsPM_Manual.lyx
  src/pspm_cfg/pspm_cfg_split_sessions.m
Labels: Bug Fixed, Waiting for Approval

#264 Update GUI font family and size
  src/pspm.fig
  src/pspm.m
  src/pspm_App.mlapp
  src/pspm_app_beta.m
  src/pspm_cfg/pspm_cfg_display.m
  src/pspm_cfg/pspm_cfg_run_display.m
  src/pspm_contrast.fig
  src/pspm_display.fig
  src/pspm_display.m
  src/pspm_display_App.mlapp
  src/pspm_init.m
  src/pspm_review.fig
  src/pspm_ui.m
  src/uitoggletool5_image.png
  src/uitoggletool6_image.png
  src/uitoggletool7_image.png
  src/uitoggletool8_image.png
Labels: Waiting for Approval

#281 Sort missing epochs in pspm_dcm
  src/pspm_dcm.m
  src/pspm_dcm_inv.m
Labels: Waiting for Approval

#282 New function template to allow users creating their own basis functions (bf) from a data vector
  src/pspm_bf_data.m
Labels: New Feature, Waiting for Approval
