Repository bachlab/PsPM, pull requests merged in 2021-06, with the labels that each got.

#174 Fix issue 133
  src/pspm_load_data.m
  src/pspm_process_illuminance.m
  src/pspm_split_sessions.m
  src/pspm_trim.m
Labels: Improvement, Waiting for Approval

#215 Fix Issue 214
  src/f_SF.m
  src/pspm_trim.m
  test/format_test_results.m
  test/pspm_test.m
  test/pspm_testcase.m
Labels: Improvement, Waiting for Approval

#230 Update UI
  src/pspm.fig
  src/pspm.m
  src/pspm_contrast.fig
Labels: Improvement, Waiting for Approval

#223 Fix Issue 213
  src/pspm.m
  src/pspm_review.fig
Labels: Improvement, Waiting for Approval

#194 Fix issue 173
  src/pspm.fig
  src/pspm.m
  src/pspm_App.mlapp
  src/pspm_cfg/pspm_cfg_artefact_rm.m
  src/pspm_cfg/pspm_cfg_data_preprocessing.m
  src/pspm_cfg/pspm_cfg_gaze_convert.m
  src/pspm_cfg/pspm_cfg_pp_scr.m
  src/pspm_cfg/pspm_cfg_run_artefact_rm.m
  src/pspm_contrast_App_report.html
  src/pspm_data_editor_App_report.html
  src/pspm_dcm.m
  src/pspm_display_App_report.html
  src/pspm_emg_pp.m
  src/pspm_pp.m
  src/pspm_scr_pp.m
  src/pspm_simple_qa.m
  src/pspm_split_sessions.m
  test/pspm_load_data_test.m
  test/pspm_pp_test.m
  test/pspm_scr_pp_test.m
  test/pspm_split_sessions_test.m
  test/pspm_test.m
Labels: Waiting for Approval

#242 Fix issue 240
  src/pspm_app_beta.m
  src/pspm_cfg/pspm_cfg_resp_pp.m
  src/pspm_cfg/pspm_cfg_run_glm_sps.m
  src/pspm_cfg/pspm_cfg_run_resp_pp.m
  src/pspm_resp_pp.m
  src/pspm_review_App_report.html
Labels: Bug Fixed

#241 Fix Issue 239
  src/pspm_cfg/pspm_cfg_run_glm_sps.m
  src/pspm_review_App_report.html
Labels: Bug Fixed

#256 Fix issue 255
  src/pspm_cfg/pspm_cfg_pp_scr.m
  test/pspm_scr_pp_test.m
Labels: Bug Fixed, Waiting for Approval

#252 fix bugs in split_sessions
  src/pspm_split_sessions.m
  src/pspm_trim.m
  test/pspm_split_sessions_test.m
Labels: Bug Fixed, Waiting for Approval

#263 Fix issue 262
  src/pspm_cfg/pspm_cfg_run_split_sessions.m
  src/pspm_cfg/pspm_cfg_split_sessions.m
Labels: Bug Fixed, Waiting for Approval
