Repository bachlab/PsPM, pull requests merged in 2021-11, with the labels that each got.

#313 Fix issue 312
  .github/workflows/main.yml
  test/import_viewpoint_test.m
  test/pspm_get_txt_test.m
  test/pspm_test_github_actions.m
Labels: Bug Fixed, Waiting for Approval

#290 Fix issue 275
  .gitignore
  src/Import/smi/import_smi.m
  src/pspm_cfg/pspm_cfg_gaze_convert.m
  src/pspm_cfg/pspm_cfg_pupil_correct.m
  src/pspm_cfg/pspm_cfg_pupil_preprocess.m
  src/pspm_compute_visual_angle.m
  src/pspm_convert_visangle2sps.m
  src/pspm_ecg_editor_App_report.html
  src/pspm_find_valid_fixations.m
  src/pspm_get_eyelink.m
  src/pspm_get_smi.m
  src/pspm_get_viewpoint.m
  src/pspm_init.m
  src/pspm_load_data.m
  src/pspm_pupil_correct.m
  src/pspm_pupil_correct_eyelink.m
  src/pspm_pupil_pp.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_get_eyelink_test.m
  test/pspm_pupil_correct_eyelink_test.m
  test/pspm_pupil_pp_test.m
Labels: Waiting for Approval

#320 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Improvement, Waiting for Approval

#315 Fix issue 314
  src/pspm_glm.m
Labels: Bug Fixed, Waiting for Approval

#325 Update test data for get_acq_test
  .gitignore
  test/pspm_get_acq_test.m
Labels: Improvement

#328 Add the editorconfig file
  .editorconfig
Labels: Improvement, Waiting for Approval

#331 DCM bugs with NaN
  src/pspm_dcm.m
  src/pspm_interpolate.m
Labels: Bug Fixed, Waiting for Approval

#327 Fix issue 326
  src/pspm_glm.m
  src/pspm_index2time.m
  src/pspm_template_options.m
  src/pspm_template_varargin.m
  src/pspm_time2index.m
Labels: Improvement, Waiting for Approval

#332 New option to normalise data in pspm_extract_segments
  src/pspm_extract_segments.m
Labels: Improvement, Waiting for Approval
