Repository bachlab/PsPM, pull requests merged in 2023-08, with the labels that each got.

#506 Fix `pspm_split_sessions`
  src/pspm_split_sessions.m
Labels: Completed & Waiting for Review

#483 Fix Issue 484 --- `pspm_sf`
  src/pspm_cfg/pspm_cfg_run_sf.m
  src/pspm_cfg/pspm_cfg_sf.m
  src/pspm_dcm_inv.m
  src/pspm_options.m
  src/pspm_overwrite.m
  src/pspm_sf.m
  src/pspm_sf_auc.m
  src/pspm_sf_dcm.m
  src/pspm_sf_mp.m
  src/pspm_sf_scl.m
Labels: Completed & Waiting for Review

#502 Fix issue 503 --- pspm_sf relevant functions
  src/pspm_cfg/pspm_cfg_sf.m
Labels: Solved

#493 Fix issue 490 --- generalising first marker channel and last data channel
  src/pspm_cfg/pspm_cfg_glm.m
  src/pspm_cfg/pspm_cfg_sf.m
  src/pspm_dcm.m
  src/pspm_glm.m
  src/pspm_merge.m
  src/pspm_options.m
  src/pspm_sf.m
  src/pspm_trim.m
Labels: Completed & Waiting for Review

#512 Fix issue 508
  src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
  src/pspm_convert_gaze_distance.m
  src/pspm_ecg_editor.m
  test/pspm_butter_test.m
  test/pspm_convert_ecg2hb_amri_test.m
  test/pspm_filtfilt_test.m
Labels: Completed & Waiting for Review

#515 Fix issue 514
  src/pspm_version.m
Labels: Completed & Waiting for Review

#510 Fix issue 509
  src/pspm_get_eyelink.m
  src/pspm_init.m
Labels: Bug

#496 Fix issue 495
  src/pspm_rev_dcm.m
Labels: Completed & Waiting for Review

#513 fix issue 499
  src/pspm_cfg/pspm_cfg_run_sf.m
  src/pspm_cfg/pspm_cfg_sf.m
  src/pspm_dcm.m
  src/pspm_get_timing.m
  src/pspm_glm.m
  src/pspm_interp1.m
  src/pspm_sf.m
  src/pspm_sf_dcm.m
Labels: Completed & Waiting for Review

#517 Fix issue 516
  src/pspm_dcm.m
  src/pspm_filtfilt.m
  src/pspm_find_channel.m
  src/pspm_gaze_pp.m
  src/pspm_glm_recon.m
  src/pspm_merge.m
  src/pspm_overwrite.m
  src/pspm_pfm.m
  src/pspm_prepdata.m
  src/pspm_pulse_convert.m
  src/pspm_pupil_pp.m
  src/pspm_ren.m
  src/pspm_rev_con.m
  src/pspm_rev_glm.m
  src/pspm_sf_auc.m
  src/pspm_sf_dcm.m
  src/pspm_sf_mp.m
  src/pspm_sf_scl.m
  src/pspm_transfer_function.m
  src/pspm_trim.m
  src/pspm_version.m
  src/pspm_write_channel.m
Labels: Completed & Waiting for Review

#488 Fix pspm_display and heart beat detection
  src/pspm_ui.m
Labels: Completed & Waiting for Review

#522 fix 504
  src/pspm_dcm.m
Labels: Completed & Waiting for Review

#520 Finalise for release 6.1
  doc/PsPM_Developers_Guide.pdf
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  doc/PsPM_References.lyx
  doc/PsPM_References.pdf
  doc/release_notes.pdf
  doc/release_notes.tex
  src/Import/smi/import_smi.m
  src/ext/matlabbatch/cfg_ui.fig
  src/ext/matlabbatch/cfg_ui.m
  src/ext/matlabbatch/cfg_ui_util.m
  src/pspm.fig
  src/pspm_appdesigner.mlapp
  src/pspm_contrast.m
  src/pspm_display.fig
  src/pspm_get_eyelink.m
  src/pspm_get_viewpoint.m
  src/pspm_guide.fig
  src/pspm_guide.m
  src/pspm_help.m
  src/pspm_init.m
  src/pspm_msg.txt
  src/pspm_quit.m
  src/pspm_ui.m
  src/pspm_ui_app.m
Labels: Completed & Waiting for Review
