Repository bachlab/PsPM, pull requests merged in 2023-09, with the labels that each got.

#528 update overwrite logic
  src/pspm_overwrite.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_interpolate_test.m
  test/pspm_load1_test.m
  test/pspm_overwrite_test.m
  test/pspm_pp_test.m
  test/pspm_process_illuminance_test.m
Labels: Improvement

#527 Fix 526
  src/pspm_get_spike.m
Labels: Completed & Waiting for Review

#529 Fix issue 75
  src/pspm_cfg/pspm_cfg_glm.m
  src/pspm_check_model.m
  src/pspm_dcm.m
  src/pspm_get_timing.m
  src/pspm_glm.m
  src/pspm_sf.m
  test/pspm_blink_saccade_filt_test.m
  test/pspm_convert_gaze_distance_test.m
  test/pspm_dcm_test.m
  test/pspm_exp_test.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_gaze_pp_test.m
  test/pspm_glm_test.m
  test/pspm_import_test.m
  test/pspm_interpolate_test.m
  test/pspm_load1_test.m
  test/pspm_load_data_test.m
  test/pspm_load_data_ui_test.m
  test/pspm_pp_test.m
  test/pspm_process_illuminance_test.m
  test/pspm_pupil_correct_eyelink_test.m
  test/pspm_pupil_pp_test.m
  test/pspm_split_sessions_test.m
Labels: Completed & Waiting for Review, Improvement

#530 document master branch handling
  doc/PsPM_release_checklist.md
Labels: Completed & Waiting for Review

#535 Fix issue 534 -- pspm_split_sessions
  src/pspm_split_sessions.m
  test/pspm_split_sessions_test.m
Labels: Completed & Waiting for Review

#532 update help texts
  src/pspm_check_model.m
  src/pspm_dcm.m
Labels: Discussion, Completed & Waiting for Review

#538 new function pspm_combine_markers
  src/pspm_appdesigner.mlapp
  src/pspm_cfg/cfg_add_module.m
  src/pspm_cfg/pspm_cfg_combine_markerchannels.m
  src/pspm_cfg/pspm_cfg_data_convert.m
  src/pspm_cfg/pspm_cfg_preparation.m
  src/pspm_cfg/pspm_cfg_run_combine_markerchannels.m
  src/pspm_cfg/pspm_cfg_run_data_editor.m
  src/pspm_cfg/pspm_cfg_tools.m
  src/pspm_combine_markerchannels.m
  src/pspm_guide.fig
  src/pspm_guide.m
  src/pspm_options.m
  test/pspm_combine_markerchannels_test.m
  test/pspm_scr_pp_test.m
  test/pspm_test.m
  test/pspm_test_github_actions.m
Labels: Improvement, Waiting for Feedbacks

#539 improve help for PS-GLM
  src/pspm_bf_psrf_fc.m
  src/pspm_cfg/pspm_cfg_glm_ps_fc.m
Labels: Completed & Waiting for Review, Improvement

#541 fix help text
  src/pspm_split_sessions.m
Labels: Bug, Completed & Waiting for Review

#542 add warning for non-zero duration in GLM
  src/pspm_glm.m
Labels: Completed & Waiting for Review, Improvement
