Repository bachlab/PsPM, pull requests merged in 2024-08, with the labels that each got.

#749 Improve pull zenodo
  src/pspm_pull_zenodo.m
Labels: Improvement, Approved

#751 Update pspm_display.m
  src/pspm_display.m
  src/pspm_glm_recon.m
  src/pspm_rev_glm.m
  src/pspm_review.m
Labels: Completed & Waiting for Review

#750 Bugfixes
  src/pspm_check_data.m
  src/pspm_dcm_inv.m
  src/pspm_scr_pp.m
Labels: Bug, Improvement, Approved

#752 Update pspm_data_editor.m
  src/pspm_data_editor.m
Labels: Completed & Waiting for Review

#753 Fix issue 674 -- update documentation
  doc/PsPM_Developers_Guide.lyx
  doc/PsPM_Developers_Guide.pdf
Labels: Completed & Waiting for Review

#754 Fix issue 692 -- remove `varargout`
  doc/PsPM_Developers_Guide.lyx
  src/pspm_data_editor.m
  src/pspm_display.m
  src/pspm_ecg_editor.m
  src/pspm_extract_segments.m
  src/pspm_filtfilt.m
  src/pspm_find_channel.m
  src/pspm_get_smr.m
  src/pspm_get_smrx.m
  src/pspm_jobman.m
  src/pspm_load1.m
  src/pspm_overwrite.m
  src/pspm_prepdata.m
  src/pspm_pulse_convert.m
  src/pspm_pupil_pp.m
  src/pspm_rev_con.m
  src/pspm_rev_dcm.m
  src/pspm_rev_glm.m
  src/pspm_review.m
  src/pspm_tam.m
  src/pspm_ui.m
Labels: Approved

#760 Fix main GUI colour issue
  src/pspm_appdesigner.mlapp
  src/pspm_ui_app.m
Labels: Completed & Waiting for Review

#756 Improvement to `pspm_text`
  src/pspm_cfg/pspm_cfg_help_format.m
  src/pspm_cfg/pspm_cfg_import.m
  src/pspm_get_acq.m
  src/pspm_get_acq_bioread.m
  src/pspm_get_acq_python.m
  src/pspm_get_acqmat.m
  src/pspm_get_biograph.m
  src/pspm_get_biosemi.m
  src/pspm_get_biotrace.m
  src/pspm_get_brainvis.m
  src/pspm_get_cnt.m
  src/pspm_get_csv.m
  src/pspm_get_edf.m
  src/pspm_get_eyelink.m
  src/pspm_get_labchart.m
  src/pspm_get_labchartmat_ext.m
  src/pspm_get_labchartmat_in.m
  src/pspm_get_mat.m
  src/pspm_get_obs.m
  src/pspm_get_physlog.m
  src/pspm_get_smi.m
  src/pspm_get_smr.m
  src/pspm_get_smrx.m
  src/pspm_get_txt.m
  src/pspm_get_vario.m
  src/pspm_get_viewpoint.m
  src/pspm_get_wdq.m
  src/pspm_get_wdq_n.m
  src/pspm_help.m
  src/pspm_help_init.m
  src/pspm_help_text.m
  src/pspm_init.m
  src/pspm_text.m
  src/pspm_trim.m
Labels: Improvement, Approved

#759 Bugfixes
  src/backroom/pspm_combine_markers.m
  src/helper/README.txt
  src/helper/SCR_f_amplitude_check.m
  src/helper/pspm_axpos.m
  src/helper/pspm_bf_Fourier.m
  src/helper/pspm_convert_illum2lum.m
  src/helper/pspm_convert_lux2cdm2.m
  src/helper/pspm_convert_mm2visdeg.m
  src/helper/pspm_find_data_epochs.m
  src/helper/pspm_get_transfer_function.m
  src/helper/pspm_ledalab.m
  src/helper/pspm_peakscore.m
  src/helper/pspm_predval.m
  src/helper/pspm_scr2ledalab.m
  src/helper/pspm_segment_mean.m
  src/helper/pspm_sf_get_theta.m
  src/helper/pspm_transfer_fit.m
  src/pspm_cfg/pspm_cfg_convert_cardiac.m
  src/pspm_cfg/pspm_cfg_data_preprocessing.m
  src/pspm_cfg/pspm_cfg_dcm.m
  src/pspm_cfg/pspm_cfg_emg_pp.m
  src/pspm_cfg/pspm_cfg_gaze_pp.m
  src/pspm_cfg/pspm_cfg_glm.m
  src/pspm_cfg/pspm_cfg_help_format.m
  src/pspm_cfg/pspm_cfg_pp_cardiac.m
  src/pspm_cfg/pspm_cfg_pp_emg.m
  src/pspm_cfg/pspm_cfg_pp_pupil.m
  src/pspm_cfg/pspm_cfg_resp_pp.m
  src/pspm_cfg/pspm_cfg_run_convert_cardiac.m
  src/pspm_cfg/pspm_cfg_run_dcm.m
  src/pspm_cfg/pspm_cfg_run_emg_pp.m
  src/pspm_cfg/pspm_cfg_run_gaze_pp.m
  src/pspm_cfg/pspm_cfg_run_sf.m
  src/pspm_cfg/pspm_cfg_run_split_sessions.m
  src/pspm_cfg/pspm_cfg_scr_pp.m
  src/pspm_cfg/pspm_cfg_selector_channel.m
  src/pspm_cfg/pspm_cfg_sf.m
  src/pspm_cfg/pspm_cfg_split_sessions.m
  src/pspm_cfg/pspm_cfg_vout_modelfile.m
  src/pspm_check_model.m
  src/pspm_convert_ecg2hb_amri.m
  src/pspm_dcm.m
  src/pspm_extract_segments.m
  src/pspm_find_valid_fixations.m
  src/pspm_gaze_pp.m
  src/pspm_init.m
  src/pspm_process_illuminance.m
  src/pspm_pupil_pp.m
  src/pspm_split_sessions.m
  test/pspm_find_valid_fixations_test.m
Labels: Bug, Completed & Waiting for Review, Improvement

#769 Error correction in `pspm_display`
  src/pspm_display.m
Labels: Completed & Waiting for Review

#772 Fix rev issue
  src/ext/matlabbatch/cfg_util.m
Labels: Completed & Waiting for Review
