Repository bachlab/PsPM, pull requests merged in 2024-09, with the labels that each got.

#766 Update `pspm_help`
  src/pspm_help.m
  src/pspm_process_illuminance.m
  src/pspm_pupil_pp_options.m
Labels: Completed & Waiting for Review

#768 fix edge case in marker value import
  src/pspm_get_biosemi.m
  src/pspm_get_biotrace.m
  src/pspm_get_cnt.m
  src/pspm_get_edf.m
  src/pspm_get_vario.m
  src/pspm_struct2vec.m
Labels: Approved

#771 Fix `pspm_extract_segments`
  src/pspm_extract_segments.m
  src/pspm_glm.m
  src/pspm_multi2index.m
  test/pspm_extract_segments_test.m
Labels: Bug, Approved

#774 Final GUI updates
  src/pspm_cfg/pspm_cfg_help_format.m
  src/pspm_cfg/pspm_cfg_process_illuminance.m
  src/pspm_cfg/pspm_cfg_pupil_preprocess.m
  src/pspm_cfg/pspm_cfg_selector_overwrite.m
  src/pspm_process_illuminance.m
Labels: Under Review

#777 Update README.md
  README.md
Labels: Completed & Waiting for Review

#767 Creat help text conversion tool
  src/pspm_doc.m
  src/pspm_find_valid_fixations.m
  src/pspm_gaze_pp.m
  test/pspm_doc_test.m
Labels: Approved

#776 Pspm struct2vec test pspm overwrite new default
  src/pspm_options.m
  src/pspm_struct2vec.m
  test/pspm_convert_gaze_test.m
  test/pspm_gaze_pp_test.m
  test/pspm_get_biosemi_test.m
  test/pspm_struct2vec_test.m
Labels: Approved

#761 Fix issue 407
  src/pspm_cfg/pspm_cfg_help_format.m
  src/pspm_data_editor.fig
  src/pspm_data_editor.m
  src/pspm_display.fig
  src/pspm_display.m
  src/pspm_ecg_editor.fig
  src/pspm_ecg_editor.m
  src/pspm_init.m
  src/pspm_review.fig
Labels: Completed & Waiting for Review

#780 New function generating help text documents
  src/pspm_doc.m
  src/pspm_doc_gen.m
  src/pspm_load_data.m
  src/pspm_pull_zenodo.m
  src/pspm_tam.m
  test/pspm_doc_test.m
  test/pspm_test.m
  test/pspm_test_github_actions.m
Labels: Completed & Waiting for Review

#773 697 write tests for missing epoch file trimming in pspm trim
  src/pspm_overwrite.m
  src/pspm_trim.m
  test/pspm_trim_test.m
Labels: Completed & Waiting for Review
