Repository bachlab/PsPM, pull requests merged in 2024-03, with the labels that each got.

#637 refactor pspm_pp
  src/pspm_cfg/pspm_cfg_artefact_rm.m
  src/pspm_cfg/pspm_cfg_run_artefact_rm.m
  src/pspm_pp.m
  src/pspm_write_channel.m
  test/pspm_pp_test.m
Labels: Approved & Waiting to Merge

#628 new function that checks/creates a python environment.
  src/pspm_check_python
Labels: Completed & Waiting for Review

#648 Fix issue 640 -- Clean get_spike
  src/pspm_get_spike.m
  src/pspm_init.m
  test/pspm_get_smr_test.m
  test/pspm_import_test.m
Labels: Discussion

#645 fix DCM for NaN data
  src/pspm_dcm.m
  test/pspm_dcm_test.m
Labels: Approved & Waiting to Merge

#650 Updated pspm_leaky_integrator and pspm_pp
  src/pspm_leaky_integrator.m
  src/pspm_pp.m
Labels: Completed & Waiting for Review

#651 fix overwriting in data editor
  src/pspm_data_editor.m
Labels: Completed & Waiting for Review, Urgent

#643 refactor get-timing & glm
  src/pspm_get_timing.m
  src/pspm_glm.m
  test/pspm_get_timing_test.m
  test26Feb2024.m
Labels: Approved

#653 Fix 606 -- GUI issue for split_sessions
  src/pspm_cfg/pspm_cfg_split_sessions.m
Labels: Completed & Waiting for Review

#661 make ECG editor compatible with PPG data
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  src/pspm_ecg_editor.m
  src/pspm_ecg_editor_App.mlapp
Labels: Urgent, Approved

#656 variable warntext_subfolder defined in pspm_init
  src/pspm_init.m
Labels: Approved

#482 Fix issue 551 -- Add NaN filtering for `pupil_pp`
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  src/pspm_cfg/pspm_cfg_pupil_preprocess.m
  src/pspm_cfg/pspm_cfg_run_pupil_preprocess.m
  src/pspm_options.m
  src/pspm_pupil_pp.m
  test/pspm_pupil_pp_test.m
Labels: Waiting for Feedbacks, Approved

#665 Fix 604 -- find valid fixations
  src/pspm_cfg/pspm_cfg_find_valid_fixations.m
  src/pspm_cfg/pspm_cfg_run_find_valid_fixations.m
  src/pspm_find_valid_fixations.m
Labels: Completed & Waiting for Review

#667 Fix 655
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  src/pspm_appdesigner.mlapp
  src/pspm_cfg/pspm_cfg_glm_sps.m
  src/pspm_guide.fig
Labels: Completed & Waiting for Review

#663 Fix 605 -- process illuminance
  src/pspm_cfg/pspm_cfg_process_illuminance.m
  src/pspm_cfg/pspm_cfg_run_proc_illuminance.m
  src/pspm_options.m
  src/pspm_process_illuminance.m
Labels: Completed & Waiting for Review

#662 Fix 607 -- GLM
  src/pspm_cfg/pspm_cfg_glm_sps.m
  test/pspm_glm_test.m
Labels: Completed & Waiting for Review

#641 Refactor `pspm_extract_segments`
  src/pspm_cfg/pspm_cfg_extract_segments.m
  src/pspm_cfg/pspm_cfg_run_extract_segments.m
  src/pspm_extract_segments.m
  src/pspm_extract_segments_core.m
  src/pspm_glm.m
  src/pspm_load1.m
  src/pspm_multi2index.m
  src/pspm_options.m
  src/pspm_remove_epochs.m
  src/pspm_tam.m
  src/pspm_time2index.m
  test/pspm_extract_segments_test.m
Labels: Approved

#612 new ppg2hb functionality using Heartpy library
  src/pspm_cfg/pspm_cfg_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_run_data_convert.m
  src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
  src/pspm_check_python.m
  src/pspm_check_python_modules.m
  src/pspm_convert_ppg2hb.m
  src/pspm_options.m
Labels: Under Review
