Repository bachlab/PsPM, pull requests merged in 2024-07, with the labels that each got.

#736 fix edge case of empty epochs file in pspm_trim
  src/pspm_trim.m
Labels: Approved

#742 Replaced video preview images with smaller versions.
  courses.markdown
Labels: Approved

#739 Fix issue 738
  src/pspm_appdesigner.mlapp
  src/pspm_display.fig
  src/pspm_ecg_editor.fig
  src/pspm_review.fig
  src/pspm_ui.m
  src/pspm_ui_app.m
Labels: Completed & Waiting for Review

#713 Fix issue 668 -- added path handling in pspm_init and pspm_quit
  src/pspm_init.m
  src/pspm_quit.m
  src/pspm_text.m
Labels: Completed & Waiting for Review

#745 Multiple bug fixes
  ppg_test.mat.zip
  src/pspm_convert_gaze.m
  src/pspm_convert_hb2hp.m
  src/pspm_dcm.m
  src/pspm_dcm_inv.m
  src/pspm_extract_segments.m
  src/pspm_get_timing.m
  src/pspm_glm.m
  src/pspm_init.m
  src/pspm_load_channel.m
  src/pspm_multi2index.m
  src/pspm_options.m
  src/pspm_pupil_pp.m
  src/pspm_remove_epochs.m
  src/pspm_resp_pp.m
  src/pspm_trim.m
  test/pspm_pupil_pp_test.m
  test/pspm_resp_pp_test.m
  test/pspm_trim_test.m
Labels: Bug, Approved

#746 Fix error of cfg_util
  src/pspm_appdesigner.mlapp
  src/pspm_init.m
  src/pspm_ui_app.m
Labels: Approved

#747 Update to support Matlab 2019
  src/pspm.m
  src/pspm_appdesigner.mlapp
  src/pspm_appdesigner2019.mlapp
  src/pspm_help.m
Labels: Completed & Waiting for Review
