Repository bachlab/PsPM, pull requests merged in 2024-04, with the labels that each got.

#681 fix pspm_pp options call
  src/pspm_pp.m
Labels: Completed & Waiting for Review

#682 Streamline channel input
  src/pspm_cfg/pspm_cfg_resp_pp.m
  src/pspm_cfg/pspm_cfg_run_find_sounds.m
  src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_run_pupil_size_convert.m
  src/pspm_cfg/pspm_cfg_split_sessions.m
  src/pspm_convert_area2diameter.m
  src/pspm_convert_au2unit.m
  src/pspm_convert_ecg2hb.m
  src/pspm_convert_ecg2hb_amri.m
  src/pspm_convert_hb2hp.m
  src/pspm_convert_ppg2hb.m
  src/pspm_find_sounds.m
  src/pspm_options.m
  src/pspm_resp_pp.m
  src/pspm_scr_pp.m
  src/pspm_split_sessions.m
  test/pspm_convert_ecg2hb_test.m
  test/pspm_find_sounds_test.m
  test/pspm_resp_pp_test.m
  test/pspm_split_sessions_test.m
Labels: Approved

#686 several bugfixes
  src/pspm_convert_ecg2hb.m
  src/pspm_dcm_inv.m
  src/pspm_extract_segments.m
  src/pspm_find_valid_fixations.m
Labels: Completed & Waiting for Review

#675 Update Python integration to PsPM UI
  src/pspm_cfg/pspm_cfg_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_python.m
  src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
  src/pspm_check_python
  src/pspm_check_python.m
  src/pspm_check_python_modules.m
  src/pspm_convert_ppg2hb.m
  src/pspm_options.m
Labels: Completed & Waiting for Review

#683 Update help text in export GUI
  src/pspm_cfg/pspm_cfg_export.m
Labels: Approved

#677 Update courses.markdown
  courses.markdown
Labels: In Progress

#658 Update python handling and tests
  .github/workflows/main.yml
  .gitignore
  doc/PsPM_Developers_Guide.lyx
  doc/PsPM_Developers_Guide.pdf
  src/pspm_cfg/pspm_cfg_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_python.m
  src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
  test/pspm_check_python_modules_test.m
  test/pspm_check_python_test.m
  test/pspm_py_find_location.py
  test/pspm_test.m
  test/pspm_test_github_actions.m
Labels: Completed & Waiting for Review

#684 Refactor `pspm_interpolate`
  src/pspm_cfg/pspm_cfg_interpolate.m
  src/pspm_cfg/pspm_cfg_run_interpolate.m
  src/pspm_interpolate.m
  src/pspm_load_channel.m
  src/pspm_options.m
  test/pspm_interpolate_test.m
  test/pspm_pupil_pp_test.m
Labels: Approved

#690 Minor improvements to `pspm_extract_segments`
  src/pspm_extract_segments.m
  src/pspm_pp.m
Labels: Approved

#691 Small fix in `pspm_select_channel`
  src/pspm_select_channels.m
Labels: Approved
