Repository bachlab/PsPM, pull requests merged in 2024-02, with the labels that each got.

#593 Create a central place for loading and checking individual channels
  .gitignore
  src/backroom/pspm_load_single_chan.m
  src/pspm_cfg/pspm_cfg_find_sounds.m
  src/pspm_cfg/pspm_cfg_pp_emg_data.m
  src/pspm_cfg/pspm_cfg_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_pp_scr.m
  src/pspm_cfg/pspm_cfg_resp_pp.m
  src/pspm_check_model.m
  src/pspm_convert_ecg2hb.m
  src/pspm_convert_ecg2hb_amri.m
  src/pspm_convert_hb2hp.m
  src/pspm_convert_ppg2hb.m
  src/pspm_dcm.m
  src/pspm_emg_pp.m
  src/pspm_extract_segments.m
  src/pspm_find_sounds.m
  src/pspm_glm.m
  src/pspm_init.m
  src/pspm_load_channel.m
  src/pspm_load_data.m
  src/pspm_options.m
  src/pspm_pupil_correct_eyelink.m
  src/pspm_pupil_pp.m
  src/pspm_resp_pp.m
  src/pspm_scr_pp.m
  src/pspm_select_channels.m
  src/pspm_sf.m
  src/pspm_tam.m
  test/pspm_convert_ecg2hb_test.m
  test/pspm_convert_hb2hp_test.m
  test/pspm_dcm_test.m
  test/pspm_find_sounds_test.m
  test/pspm_pupil_correct_eyelink_test.m
Labels: Completed & Waiting for Review

#562 Fix issue 559
  doc/Figures/YY1_import.png
  doc/Figures/YY1_import_text_too_small.png
  doc/Figures/YY2_trim.png
  doc/Figures/YY2_trim_text_too_small.png
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  src/pspm_cfg/pspm_cfg_run_artefact_rm.m
  src/pspm_cfg/pspm_cfg_run_combine_markerchannels.m
  src/pspm_cfg/pspm_cfg_run_contrast1.m
  src/pspm_cfg/pspm_cfg_run_contrast2.m
  src/pspm_cfg/pspm_cfg_run_data_convert.m
  src/pspm_cfg/pspm_cfg_run_data_editor.m
  src/pspm_cfg/pspm_cfg_run_dcm.m
  src/pspm_cfg/pspm_cfg_run_downsample.m
  src/pspm_cfg/pspm_cfg_run_ecg_editor.m
  src/pspm_cfg/pspm_cfg_run_export.m
  src/pspm_cfg/pspm_cfg_run_extract_segments.m
  src/pspm_cfg/pspm_cfg_run_find_sounds.m
  src/pspm_cfg/pspm_cfg_run_find_valid_fixations.m
  src/pspm_cfg/pspm_cfg_run_gaze_convert.m
  src/pspm_cfg/pspm_cfg_run_get_markerinfo.m
  src/pspm_cfg/pspm_cfg_run_glm.m
  src/pspm_cfg/pspm_cfg_run_glm_hp_e.m
  src/pspm_cfg/pspm_cfg_run_glm_hp_fc.m
  src/pspm_cfg/pspm_cfg_run_glm_ps_fc.m
  src/pspm_cfg/pspm_cfg_run_glm_ra_e.m
  src/pspm_cfg/pspm_cfg_run_glm_ra_fc.m
  src/pspm_cfg/pspm_cfg_run_glm_rfr_e.m
  src/pspm_cfg/pspm_cfg_run_glm_rp_e.m
  src/pspm_cfg/pspm_cfg_run_glm_scr.m
  src/pspm_cfg/pspm_cfg_run_glm_sebr.m
  src/pspm_cfg/pspm_cfg_run_glm_sps.m
  src/pspm_cfg/pspm_cfg_run_import.m
  src/pspm_cfg/pspm_cfg_run_interpolate.m
  src/pspm_cfg/pspm_cfg_run_merge.m
  src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_run_proc_illuminance.m
  src/pspm_cfg/pspm_cfg_run_pupil_correct.m
  src/pspm_cfg/pspm_cfg_run_pupil_preprocess.m
  src/pspm_cfg/pspm_cfg_run_pupil_size_convert.m
  src/pspm_cfg/pspm_cfg_run_rename.m
  src/pspm_cfg/pspm_cfg_run_review1.m
  src/pspm_cfg/pspm_cfg_run_review2.m
  src/pspm_cfg/pspm_cfg_run_segment_mean.m
  src/pspm_cfg/pspm_cfg_run_sf.m
  src/pspm_cfg/pspm_cfg_run_trim.m
  src/pspm_cfg/pspm_cfg_second_level.m
  src/pspm_cfg/pspm_cfg_split_sessions.m
  src/pspm_cfg/pspm_update_struct.m
  src/pspm_convert_ppg2hb.m
  src/pspm_find_sounds.m
  src/pspm_interpolate.m
  src/pspm_overwrite.m
  test/pspm_test.m
  test/pspm_test_github_actions.m
  test/pspm_update_struct_test.m
Labels: Completed & Waiting for Review

#620 Update find_valid_fixations & remove eyetracker pp channel types
  src/pspm_find_valid_fixations.m
  src/pspm_gaze_pp.m
  src/pspm_init.m
  src/pspm_load_channel.m
  src/pspm_options.m
  src/pspm_pupil_pp.m
  src/pspm_scr_pp.m
  src/pspm_select_channels.m
  src/pspm_update_channeltype.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_gaze_pp_test.m
Labels: Completed & Waiting for Review

#619 New function pspm_extract_segments_core
  README.md
  src/pspm_extract_segments_core.m
  test/pspm_extract_segments_core_test.m
Labels: Completed & Waiting for Review

#625 fix import output
  src/pspm_import.m
Labels: Completed & Waiting for Review

#627 update DCM
  src/pspm_dcm.m
  src/pspm_extract_segments_core.m
  src/pspm_time2index.m
  test/pspm_dcm_test.m
Labels: Completed & Waiting for Review

#621 Update pupil_pp logic
  src/pspm_find_eye.m
  src/pspm_find_valid_fixations.m
  src/pspm_gaze_pp.m
  src/pspm_load_gaze.m
  src/pspm_options.m
  src/pspm_pupil_correct_eyelink.m
  src/pspm_pupil_pp.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_gaze_pp_test.m
  test/pspm_pupil_pp_test.m
Labels: Completed & Waiting for Review

#611 new function to convert missing epochs to a logical index
  src/pspm_epochs2logical.m
  test/pspm_epochs2logical_test.m
  test/pspm_test.m
  test/pspm_test_github_actions.m
Labels: Reviewed & Waiting to Merge

#623 Update remaining convert functions
  doc/PsPM_Developers_Guide.lyx
  doc/PsPM_Developers_Guide.pdf
  doc/PsPM_Manual.lyx
  doc/PsPM_References.lyx
  src/pspm_cfg/pspm_cfg_run_gaze_convert.m
  src/pspm_compute_visual_angle.m
  src/pspm_convert_area2diameter.m
  src/pspm_convert_au2unit.m
  src/pspm_convert_ecg2hb_amri.m
  src/pspm_convert_gaze.m
  src/pspm_convert_gaze_distance.m
  src/pspm_convert_pixel2unit.m
  src/pspm_convert_pixel2unit_core.m
  src/pspm_convert_visangle2sps.m
  src/pspm_convert_visangle2sps_core.m
  src/pspm_convert_visual_angle_core.m
  src/pspm_find_valid_fixations.m
  src/pspm_load_data.m
  src/pspm_options.m
  src/pspm_select_channels.m
  test/pspm_convert_gaze_distance_test.m
  test/pspm_convert_gaze_test.m
  test/pspm_convert_pixel2unit_test.m
  test/pspm_find_sounds_test.m
  test/pspm_gaze_pp_test.m
  test/pspm_pupil_correct_eyelink_test.m
  test/pspm_test.m
  test/pspm_test_github_actions.m
Labels: Approved & Waiting to Merge

#551 Fix issue 548 -- scr_pp's clipping detection
  src/pspm_options.m
  src/pspm_scr_pp.m
  test26Feb2024.m
Labels: Completed & Waiting for Review

#636 Enable denoising for all continuous marker channels
  src/pspm_extract_segments.m
  src/pspm_get_events.m
  src/pspm_get_spike.m
  src/pspm_import.m
  test/pspm_get_events_test.m
Labels: Approved & Waiting to Merge

#630 New function for simple pulling of PsPM development data sets from zenodo
  src/pspm_pull_zenodo.m
Labels: Completed & Waiting for Review
