Repository bachlab/PsPM, pull requests merged in 2024-01, with the labels that each got.

#568 Use missing information for dcm in pspm_extract_segmenets
  src/pspm_extract_segments.m
Labels: Completed & Waiting for Review

#564 adapt pspm_split_sessions
  src/pspm_split_sessions.m
  test/pspm_split_sessions_test.m
Labels: Approved

#566 fix issue 565
  src/pspm_dcm.m
Labels: Approved

#572 initial commit to fix #571
  src/pspm_dcm.m
Labels: Approved

#575 Implement model checks for trial-average model
  doc/PsPM-help_text_progress.xlsx
  doc/PsPM_Developers_Guide.pdf
  doc/PsPM_Manual.pdf
  doc/PsPM_References.lyx
  doc/PsPM_References.pdf
  doc/pspm_options_subfields.numbers
  src/pspm_check_model.m
  src/pspm_glm.m
  src/pspm_init.m
  src/pspm_load1.m
  src/pspm_options.m
  src/pspm_pfm.m
  src/pspm_tam.m
  test/pspm_load1_test.m
Labels: Approved

#582 Fix 578
  src/pspm_check_model.m
  src/pspm_con1.m
  src/pspm_init.m
  src/pspm_load_data.m
  src/pspm_overwrite.m
  src/pspm_pupil_correct_eyelink.m
  src/pspm_pupil_pp.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_interpolate_test.m
  test/pspm_load1_test.m
  test/pspm_pp_test.m
  test/pspm_process_illuminance_test.m
  test/pspm_pupil_correct_eyelink_test.m
  test/pspm_pupil_pp_test.m
Labels: Completed & Waiting for Review

#576 Ensure pupil processing functions produce pupil, not pupil_pp, channel output
  src/pspm_check_model.m
  src/pspm_con1.m
  src/pspm_init.m
  src/pspm_load_data.m
  src/pspm_overwrite.m
  src/pspm_pupil_correct_eyelink.m
  src/pspm_pupil_pp.m
  test/pspm_find_valid_fixations_test.m
  test/pspm_interpolate_test.m
  test/pspm_load1_test.m
  test/pspm_pp_test.m
  test/pspm_process_illuminance_test.m
  test/pspm_pupil_correct_eyelink_test.m
  test/pspm_pupil_pp_test.m
Labels: Completed & Waiting for Review, Urgent

#553 Fix issue 545 -- outdated documentation
  .gitignore
  doc/Figures/YY1_import.png
  doc/Figures/YY1_import_legacy.png
  doc/Figures/YY2_trim.png
  doc/Figures/YY2_trim_legacy.png
  doc/Figures/YY3_glm.png
  doc/Figures/YY3_glm_legacy.png
  doc/PsPM_Developers_Guide.pdf
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  src/pspm_cfg/pspm_cfg_artefact_rm.m
  src/pspm_cfg/pspm_cfg_import.m
  src/pspm_cfg/pspm_cfg_split_sessions.m
  src/pspm_cfg/pspm_cfg_trim.m
Labels: In Progress

#588 fix 587
  src/pspm_check_model.m
Labels: Bug, Urgent

#592 Fix issue 590 -- convert_hb2hp
  src/pspm_convert_hb2hp.m
  src/pspm_quit.m
  test/pspm_convert_hb2hp_test.m
Labels: Improvement

#595 fix bug in selection of marker channel in pspm_glm
  src/pspm_glm.m
Labels: Bug, Completed & Waiting for Review, Urgent

#598 Fix issue 596
  src/pspm_cfg/pspm_cfg_pp_emg.m
  src/pspm_cfg/pspm_cfg_pp_emg_data.m
  src/pspm_cfg/pspm_cfg_run_pp_emg_data.m
  src/pspm_pp.m
Labels: Bug, GUI Issue

#594 fix bug in DCM
  src/pspm_dcm.m
Labels: Bug, Completed & Waiting for Review, Urgent

#615 Update documents for v6.1.2
  doc/PsPM_Developers_Guide.lyx
  doc/PsPM_Developers_Guide.pdf
  doc/PsPM_Manual.lyx
  doc/PsPM_Manual.pdf
  doc/PsPM_References.lyx
  doc/PsPM_References.pdf
  doc/release_notes.pdf
  doc/release_notes.tex
Labels: Completed & Waiting for Review
