Repository bachlab/PsPM, pull requests merged in 2024-06, with the labels that each got.

#703 update references in help texts
  src/pspm_convert_ecg2hb.m
  src/pspm_convert_ecg2hb_amri.m
  src/pspm_convert_hb2hp.m
  src/pspm_dcm.m
  src/pspm_emg_pp.m
  src/pspm_glm.m
  src/pspm_process_illuminance.m
  src/pspm_resp_pp.m
  src/pspm_sf.m
  src/pspm_sf_auc.m
  src/pspm_sf_dcm.m
  src/pspm_sf_mp.m
  src/pspm_tam.m
Labels: Completed & Waiting for Review

#700 Improve pmod handling in `pspm_glm`
  src/pspm_get_timing.m
  test/pspm_get_timing_test.m
  test/pspm_glm_test.m
Labels: Completed & Waiting for Review

#714 Fix issue 698 -- new GUI
  src/pspm.m
  src/pspm_appdesigner.mlapp
  src/pspm_ui_app.m
Labels: Approved

#709 Wrong y label corrected
  src/pspm_data_editor.m
Labels: Approved

#716 Fix issue 698 - new UI
  src/pspm_appdesigner.mlapp
  src/pspm_ui_app.m
Labels: Bug

#710 fix options handling in pspm_extract_segments
  src/pspm_extract_segments.m
  test/pspm_extract_segments_test.m
Labels: Approved

#706 Cleanup GUI
  src/pspm_cfg/pspm_cfg.m
  src/pspm_cfg/pspm_cfg_combine_markerchannels.m
  src/pspm_cfg/pspm_cfg_contrast1.m
  src/pspm_cfg/pspm_cfg_contrast2.m
  src/pspm_cfg/pspm_cfg_data_design_selector.m
  src/pspm_cfg/pspm_cfg_extract_segments.m
  src/pspm_cfg/pspm_cfg_filtering.m
  src/pspm_cfg/pspm_cfg_first_level.m
  src/pspm_cfg/pspm_cfg_glm.m
  src/pspm_cfg/pspm_cfg_glm_ps_fc.m
  src/pspm_cfg/pspm_cfg_glm_sebr.m
  src/pspm_cfg/pspm_cfg_glm_sps.m
  src/pspm_cfg/pspm_cfg_run_extract_segments.m
  src/pspm_cfg/pspm_cfg_run_filtering.m
  src/pspm_cfg/pspm_cfg_run_glm.m
  src/pspm_cfg/pspm_cfg_run_review2.m
  src/pspm_cfg/pspm_cfg_run_segment_mean.m
  src/pspm_cfg/pspm_cfg_second_level.m
  src/pspm_cfg/pspm_cfg_tools.m
  src/pspm_con1.m
  src/pspm_con2.m
  src/pspm_contrast.fig
  src/pspm_contrast.m
  src/pspm_contrast_App.mlapp
  src/pspm_rev2.m
Labels: Completed & Waiting for Review

#723 Fix issue 718 -- `display`
  src/pspm_display.m
Labels: Completed & Waiting for Review

#724 Fix issue 717 -- `data_editor`
  src/pspm_data_editor.m
Labels: Completed & Waiting for Review

#659 New function which directly imports acq file data
  doc/PsPM_Developers_Guide.lyx
  doc/PsPM_Developers_Guide.pdf
  ppg_test.mat.zip
  src/Import/acq/acqread_python.m
  src/pspm_cfg/pspm_cfg_import.m
  src/pspm_cfg/pspm_cfg_pp_heart_data.m
  src/pspm_cfg/pspm_cfg_python.m
  src/pspm_cfg/pspm_cfg_run_import.m
  src/pspm_check_python_modules.m
  src/pspm_get_acq.m
  src/pspm_init.m
  src/pspm_options.m
  src/pspm_text.m
  test/pspm_get_acq_python_test.m
Labels: Approved

#729 add new HPR-reward model
  src/pspm_bf_hprf_rew.m
  src/pspm_cfg/pspm_cfg_first_level_hp.m
  src/pspm_cfg/pspm_cfg_glm_hp_rew.m
  src/pspm_cfg/pspm_cfg_run_glm_hp_rew.m
  src/pspm_glm.m
  src/pspm_init.m
Labels: Approved
