Repository bachlab/PsPM, pull requests merged in 2025-02, with the labels that each got.

#823 Update pspm document generation functions for new website
  src/pspm_doc.m
  src/pspm_doc_gen.m
  src/pspm_expand_epochs.m
  test/pspm_doc_test.m
Labels: Approved

#721 Release 7.0
  doc/release_notes.pdf
  doc/release_notes.tex
  src/pspm_cfg/pspm_cfg_resp_pp.m
  src/pspm_check_data.m
  src/pspm_show_forum.m
Labels: In Progress

#826 Update pspm_installer
  src/helper/PsPM_installer.m
Labels: Approved

#832 fix help text in `pspm_get_timing`
  src/pspm_get_timing.m
Labels: Completed & Waiting for Review
